In [1]:
import requests
import pandas as pd

r = requests.get('https://api.sleeper.app/v1/players/nfl')
r.json()
player_df=pd.read_json(r.text, orient='index')

/tmp/ipykernel_1853/1655298528.py:6: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df=pd.read_json(r.text, orient='index')
/tmp/ipykernel_1853/1655298528.py:6: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  player_df=pd.read_json(r.text, orient='index')
/tmp/ipykernel_1853/1655298528.py:6: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  player_df=pd.read_json(r.text, orient='index')
/tmp/ipykernel_1853/1655298528.py:6: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  player_df=pd.read_json(r.text, orient='index')

In [2]:
player_df.reset_index(inplace=True)

In [3]:
player_df

,index,search_full_name,birth_city,search_first_name,fantasy_data_id,metadata,depth_chart_order,active,team_changed_at,player_id,...,swish_id,high_school,college,number,first_name,birth_date,gsis_id,hashtag,team,fantasy_positions
0,6462,ellisrichardson,NaN,ellis,21427.0,{'channel_id': '1116853254748110848'},NaN,True,NaT,6462,...,NaN,Douglas County,Georgia Southern,45.0,Ellis,1995-02-12,00-0035057,#ellisrichardson-NFL-FA-45,None,[TE]
1,11255,nickamoah,NaN,nick,NaN,{'channel_id': '1116852669114220544'},NaN,True,NaT,11255,...,1052592.0,Davis (CA),UC Davis,63.0,Nick,None,None,#nickamoah-NFL-FA-63,None,[OL]
2,8842,malkelmmorrison,NaN,malkelm,NaN,"{'channel_id': '1116853537213513728', 'years_e...",NaN,True,NaT,8842,...,1131137.0,Iona Prep (NY),Army,0.0,Malkelm,None,None,#malkelmmorrison-NFL-FA-0,None,[DB]
3,7926,carltucker,NaN,carl,NaN,{'channel_id': '1116853436709601280'},NaN,True,NaT,7926,...,866047.0,Hough (NC),Alabama,0.0,Carl,1997-02-06,None,#carltucker-NFL-FA-0,None,[TE]
4,1875,cjmosley,NaN,cj,16093.0,"{'channel_id': '1113708745461886977', 'rookie_...",1.0,True,NaT,1875,...,557173.0,Theodore (AL),Alabama,57.0,C.J.,1992-06-19,00-0031296,#cjmosley-NFL-NYJ-57,NYJ,[LB]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10584,CHI,NaN,NaN,NaN,NaN,NaN,NaN,True,NaT,CHI,...,NaN,NaN,NaN,NaN,Chicago,NaN,NaN,NaN,CHI,[DEF]
10585,CIN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaT,CIN,...,NaN,NaN,NaN,NaN,Cincinnati,NaN,NaN,NaN,CIN,[DEF]
10586,DEN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaT,DEN,...,NaN,NaN,NaN,NaN,Denver,NaN,NaN,NaN,DEN,[DEF]
10587,KC,NaN,NaN,NaN,NaN,NaN,NaN,True,NaT,KC,...,NaN,NaN,NaN,NaN,Kansas City,NaN,NaN,NaN,KC,[DEF]
10588,MIN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaT,MIN,...,NaN,NaN,NaN,NaN,Minnesota,NaN,NaN,NaN,MIN,[DEF]

In [4]:
import pandas as pd
from roster import Roster
from tradevalue import TradeValue

In [5]:
from tradevalue import TradeValue

TradeValue_Class = TradeValue("https://www.thescore.com/news/3115573")
TradeValue_df = TradeValue_Class.all_dfs

/home/jamesyou/FantasyFootball/tradevalue.py:15: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 15 of the file /home/jamesyou/FantasyFootball/tradevalue.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(html_page)
INFO:root:{'base': 'https://www.thescore.com/news/3115573', 'RB': 'https://www.thescore.com/news/2817987', 'WR': 'https://www.thescore.com/news/2817988', 'TE': 'https://www.thescore.com/news/2817989', 'Draft Picks': 'https://www.thescore.com/news/2817990'}

In [6]:
TradeValue_df

                Player  Value     Position
0           Josh Allen   64.0         base
1        Lamar Jackson   60.0         base
2       Jayden Daniels   59.0         base
3          C.J. Stroud   57.0         base
4   Patrick Mahomes II   56.0         base
..                 ...    ...          ...
7                  NaN    6.0  Draft Picks
8                  NaN    4.0  Draft Picks
9                  NaN    3.0  Draft Picks
10                 NaN    2.0  Draft Picks
11                 NaN    1.0  Draft Picks

[352 rows x 3 columns]

In [7]:
selected_items = ["QB", "RB", "WR", "TE", "base"]
TradeValue_df=TradeValue_df[TradeValue_df["Position"].isin(selected_items)]
player_df=player_df[player_df["position"].isin(selected_items)]

In [8]:
TradeValue_df

                Player  Value Position
0           Josh Allen   64.0     base
1        Lamar Jackson   60.0     base
2       Jayden Daniels   59.0     base
3          C.J. Stroud   57.0     base
4   Patrick Mahomes II   56.0     base
..                 ...    ...      ...
55       Charlie Kolar    0.0       TE
56        Hayden Hurst    0.0       TE
57       Adam Trautman    0.0       TE
58      Elijah Higgins    0.0       TE
59        Jordan Akins    0.0       TE

[340 rows x 3 columns]

In [9]:
def col_replace(df, column_name):
    df[column_name] = df[column_name].str.replace('.', '', regex=False)
    df[column_name] = df[column_name].str.replace('Kenneth', 'Ken', regex=False)
    df[column_name] = df[column_name].str.replace(' Jr', '', regex=False)
    df[column_name] = df[column_name].str.rstrip(' III')
    df[column_name] = df[column_name].str.rstrip(' II')
    return df

In [10]:
TradeValue_df = col_replace(TradeValue_df, 'Player')
player_df = col_replace(player_df, 'full_name')

/tmp/ipykernel_1853/2038393473.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.replace('.', '', regex=False)
/tmp/ipykernel_1853/2038393473.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.replace('Kenneth', 'Ken', regex=False)
/tmp/ipykernel_1853/2038393473.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.replace(' Jr', '', regex=False)
/tmp/ipykernel_1853/2038393473.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.rstrip(' III')
/tmp/ipykernel_1853/2038393473.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.rstrip(' II')

In [11]:
TradeValueIndexDF=TradeValue_df.merge(player_df, left_on='Player', right_on='full_name', how='left')[["Player", "Value", "Position", "index"]]

In [12]:
r = requests.get('https://api.sleeper.app/v1/league/1048489707518140416/rosters')
r.json()

[{'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'WWWLWWWWWWLWWWWWWW', 'streak': '7W'},
  'owner_id': '703398039083122688',
  'player_map': None,
  'players': ['10223',
   '10444',
   '11604',
   '11627',
   '1466',
   '1689',
   '19',
   '2078',
   '2306',
   '4018',
   '4866',
   '4892',
   '4943',
   '5010',
   '5133',
   '5870',
   '5927',
   '6111',
   '6768',
   '6783',
   '6803',
   '6819',
   '7527',
   '7528',
   '7543',
   '8143',
   '8144',
   '8219',
   '8917',
   '9500',
   '9506'],
  'reserve': ['1689', '6803', '8219'],
  'roster_id': 1,
  'settings': {'fpts': 1541,
   'fpts_against': 1329,
   'fpts_against_decimal': 60,
   'fpts_decimal': 34,
   'losses': 2,
   'ppts': 1876,
   'ppts_decimal': 48,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 99,
   'waiver_position': 7,
   'wins': 16},
  'starters': ['4943',
   '4018',
   '4866',
   '9500',
   '8144',
   '6819',
   '1466',
   '5927',
   '7528',
   '5010',
   '6768'],
  'taxi': ['10223', '10444', '11627']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'LLLLLLLLLLLLLLLLLL', 'streak': '18L'},
  'owner_id': '1085650223977885696',
  'player_map': None,
  'players': ['11640',
   '9753',
   '9502',
   '9482',
   '9497',
   '8172',
   '11621',
   '11625',
   '8204',
   '11573',
   '11637',
   '11582',
   '11729',
   '8121',
   '7670',
   '11603',
   '11631',
   '11581',
   '7568',
   '11559',
   '9494',
   '8142',
   '8132',
   '7562',
   '11638',
   '11567',
   '8117',
   '8125',
   '8147',
   '11635',
   '7608',
   '11610',
   '11636'],
  'reserve': ['11567', '11581', '7568', '9482'],
  'roster_id': 2,
  'settings': {'fpts': 668,
   'fpts_against': 1280,
   'fpts_against_decimal': 22,
   'fpts_decimal': 96,
   'losses': 18,
   'ppts': 1003,
   'ppts_decimal': 8,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 92,
   'waiver_position': 12,
   'wins': 0},
  'starters': ['0',
   '8132',
   '9753',
   '9502',
   '7670',
   '8121',
   '11603',
   '7562',
   '11625',
   '8117',
   '8142'],
  'taxi': ['11559', '11631', '11635', '11637']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'LWLLLLWLWWWWLLWLLL', 'streak': '3L'},
  'owner_id': '474354594260971520',
  'player_map': None,
  'players': ['10213',
   '10222',
   '10235',
   '10863',
   '10871',
   '11439',
   '11560',
   '11592',
   '11624',
   '11626',
   '1339',
   '4454',
   '5857',
   '5985',
   '6149',
   '6770',
   '7526',
   '7610',
   '8119',
   '8138',
   '8148',
   '9220',
   '9224',
   '9229',
   '9479',
   '9481',
   '9487',
   '9488'],
  'reserve': ['9481'],
  'roster_id': 3,
  'settings': {'fpts': 1290,
   'fpts_against': 1247,
   'fpts_against_decimal': 46,
   'fpts_decimal': 4,
   'losses': 11,
   'ppts': 1513,
   'ppts_decimal': 74,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 4,
   'waiver_position': 3,
   'wins': 7},
  'starters': ['6770',
   '8138',
   '9224',
   '10222',
   '7526',
   '9488',
   '1339',
   '11626',
   '6149',
   '11624',
   '11560'],
  'taxi': ['10871', '9479']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'WLLWWWLWLLLLWWWWLW', 'streak': '1W'},
  'owner_id': '865796491103596544',
  'player_map': None,
  'players': ['10857',
   '10859',
   '10866',
   '11256',
   '11620',
   '11646',
   '2197',
   '2307',
   '4029',
   '4046',
   '4082',
   '5022',
   '5248',
   '5846',
   '5937',
   '5967',
   '6694',
   '6845',
   '6904',
   '6943',
   '6945',
   '7561',
   '7593',
   '7596',
   '8111',
   '8112',
   '8150',
   '8228',
   '829',
   '9504',
   '9756'],
  'reserve': ['2197', '5248', '6845', '7561'],
  'roster_id': 4,
  'settings': {'fpts': 1412,
   'fpts_against': 1321,
   'fpts_against_decimal': 12,
   'fpts_decimal': 82,
   'losses': 8,
   'ppts': 1589,
   'ppts_decimal': 80,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 36,
   'waiver_position': 6,
   'wins': 10},
  'starters': ['6904',
   '5967',
   '8150',
   '8112',
   '9756',
   '11620',
   '10859',
   '6943',
   '8111',
   '5022',
   '4046'],
  'taxi': ['10857', '10866', '11256']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'LLLLLLLLLLLLWWLLWL', 'streak': '1L'},
  'owner_id': '476935207337848832',
  'player_map': None,
  'players': ['4314',
   '4464',
   '3200',
   '4098',
   '7594',
   '4144',
   '11600',
   '5012',
   '8230',
   '11562',
   '10212',
   '9757',
   '7571',
   '4381',
   '10214',
   '6869',
   '4973',
   '11565',
   '11605',
   '11596',
   '11586',
   '8208',
   '8135',
   '8137',
   '11630',
   '9228',
   '11651',
   '11618',
   '9486',
   '8131',
   '10232',
   '7828',
   '8134'],
  'reserve': ['11565', '11630', '8135', '8208'],
  'roster_id': 5,
  'settings': {'fpts': 853,
   'fpts_against': 1229,
   'fpts_against_decimal': 14,
   'fpts_decimal': 42,
   'losses': 15,
   'ppts': 1179,
   'ppts_decimal': 76,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 31,
   'waiver_position': 9,
   'wins': 3},
  'starters': ['4381',
   '8230',
   '7594',
   '8134',
   '9486',
   '10232',
   '5012',
   '4098',
   '4144',
   '8131',
   '7571'],
  'taxi': ['11596', '11600', '11618', '11651']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'WWWWLWWWLLLLLLWLWW', 'streak': '2W'},
  'owner_id': '867881987678076928',
  'player_map': None,
  'players': ['11595',
   '11599',
   '11619',
   '11629',
   '11650',
   '1234',
   '1373',
   '1479',
   '2028',
   '2309',
   '3164',
   '3257',
   '4034',
   '4035',
   '4039',
   '4137',
   '4147',
   '4950',
   '5001',
   '5045',
   '5096',
   '5906',
   '5947',
   '6151',
   '6813',
   '6828',
   '7601',
   '8126',
   '8130',
   '8225',
   '8408',
   '9999'],
  'reserve': ['11595', '4950', '6828', '7601'],
  'roster_id': 6,
  'settings': {'fpts': 1395,
   'fpts_against': 1296,
   'fpts_against_decimal': 88,
   'fpts_decimal': 94,
   'losses': 8,
   'ppts': 1572,
   'ppts_decimal': 88,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 34,
   'waiver_position': 5,
   'wins': 10},
  'starters': ['2028',
   '4035',
   '4137',
   '5947',
   '8126',
   '5045',
   '8130',
   '1479',
   '4039',
   '6813',
   '1373'],
  'taxi': ['11599', '11619', '11629', '11650']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'LLWWLLLWWWLLLWLWWW', 'streak': '3W'},
  'owner_id': '713130454613573632',
  'player_map': None,
  'players': ['10231',
   '11570',
   '11574',
   '11589',
   '11647',
   '11748',
   '11783',
   '2133',
   '3286',
   '4017',
   '4040',
   '4066',
   '4718',
   '4972',
   '5848',
   '5850',
   '5970',
   '5995',
   '6806',
   '7021',
   '7523',
   '7564',
   '7585',
   '7588',
   '7694',
   '7989',
   '8110',
   '8154',
   '9221'],
  'reserve': ['5848'],
  'roster_id': 7,
  'settings': {'fpts': 1394,
   'fpts_against': 1416,
   'fpts_against_decimal': 40,
   'fpts_decimal': 32,
   'losses': 9,
   'ppts': 1560,
   'ppts_decimal': 20,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 100,
   'waiver_position': 4,
   'wins': 9},
  'starters': ['7523',
   '7588',
   '9221',
   '7564',
   '2133',
   '3286',
   '4066',
   '6806',
   '8110',
   '7021',
   '4972'],
  'taxi': ['11570', '11574', '11783']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'WWWWLWWWLWWWLLWWWW', 'streak': '4W'},
  'owner_id': '516828521139388416',
  'player_map': None,
  'players': ['10225',
   '11510',
   '11566',
   '11575',
   '11597',
   '11632',
   '11643',
   '11645',
   '11895',
   '1352',
   '2216',
   '2449',
   '3214',
   '421',
   '6786',
   '6797',
   '6801',
   '6826',
   '7002',
   '7525',
   '7611',
   '8129',
   '8136',
   '8151',
   '8162',
   '9225',
   '9226',
   '9492',
   '9505'],
  'reserve': ['2216', '2449'],
  'roster_id': 8,
  'settings': {'fpts': 1557,
   'fpts_against': 1378,
   'fpts_against_decimal': 26,
   'fpts_decimal': 42,
   'losses': 4,
   'ppts': 1820,
   'ppts_decimal': 50,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 11,
   'waiver_position': 8,
   'wins': 14},
  'starters': ['11566',
   '8151',
   '9226',
   '6786',
   '11632',
   '7525',
   '6826',
   '8136',
   '7611',
   '3214',
   '421'],
  'taxi': ['11575', '11597', '11645']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'LLLLWLLLWLWLWLLLLL', 'streak': '5L'},
  'owner_id': '411785392388325376',
  'player_map': None,
  'players': ['10218',
   '11435',
   '11576',
   '11616',
   '11655',
   '2711',
   '3294',
   '3321',
   '4234',
   '4274',
   '4351',
   '4574',
   '4663',
   '5113',
   '5185',
   '5374',
   '5844',
   '5854',
   '5938',
   '6804',
   '8116',
   '8161',
   '8205',
   '8249',
   '9230',
   '9484',
   '9501',
   '9758',
   '9997'],
  'reserve': ['5185', '8205'],
  'roster_id': 9,
  'settings': {'fpts': 1139,
   'fpts_against': 1399,
   'fpts_against_decimal': 58,
   'fpts_decimal': 16,
   'losses': 14,
   'ppts': 1334,
   'ppts_decimal': 22,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 72,
   'waiver_position': 11,
   'wins': 4},
  'starters': ['9758',
   '4663',
   '11655',
   '9997',
   '3321',
   '9501',
   '5844',
   '11576',
   '4234',
   '4351',
   '6804'],
  'taxi': ['11616', '9230']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'allow_pn_inactive_starters': 'on',
   'allow_pn_player_injury_status': 'off',
   'allow_pn_scoring': 'off',
   'p_nick_4381': '24 3rd',
   'p_nick_5955': '',
   'p_nick_6853': '',
   'p_nick_7670': '',
   'p_nick_8118': '',
   'p_nick_8134': '',
   'record': 'WWWWWWWLWWWWWWWWLW',
   'restrict_pn_scoring_starters_only': 'on',
   'streak': '1W'},
  'owner_id': '462028117192470528',
  'player_map': None,
  'players': ['10862',
   '11306',
   '11579',
   '11590',
   '11628',
   '11644',
   '11834',
   '1426',
   '3198',
   '4217',
   '4981',
   '4984',
   '5849',
   '6136',
   '6794',
   '6820',
   '6853',
   '6865',
   '6938',
   '7049',
   '7553',
   '8145',
   '8146',
   '8155',
   '8168',
   '9480',
   '9493',
   '9509',
   '96',
   '9754'],
  'reserve': ['8168'],
  'roster_id': 10,
  'settings': {'fpts': 1627,
   'fpts_against': 1180,
   'fpts_against_decimal': 80,
   'fpts_decimal': 90,
   'losses': 2,
   'ppts': 1920,
   'ppts_decimal': 82,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 16,
   'waiver_position': 2,
   'wins': 16},
  'starters': ['4984',
   '9509',
   '8155',
   '6794',
   '8146',
   '11628',
   '7553',
   '9493',
   '3198',
   '1426',
   '5849'],
  'taxi': ['10862', '11590', '11644', '9480']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'LLLLWLLLLLWWLLLLWL', 'streak': '1L'},
  'owner_id': '473952170073387008',
  'player_map': None,
  'players': ['10236',
   '11564',
   '11577',
   '11617',
   '1166',
   '1837',
   '2374',
   '3163',
   '4037',
   '4068',
   '4080',
   '4089',
   '4111',
   '4149',
   '4171',
   '4988',
   '4993',
   '5872',
   '5987',
   '6011',
   '6130',
   '6790',
   '7066',
   '7547',
   '8139',
   '8167',
   '8210',
   '9508',
   '9998'],
  'reserve': ['4171'],
  'roster_id': 11,
  'settings': {'fpts': 1235,
   'fpts_against': 1387,
   'fpts_against_decimal': 12,
   'fpts_decimal': 50,
   'losses': 14,
   'ppts': 1478,
   'ppts_decimal': 70,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 0,
   'waiver_position': 1,
   'wins': 4},
  'starters': ['1166',
   '6790',
   '5987',
   '8167',
   '2374',
   '7547',
   '10236',
   '4993',
   '4080',
   '4988',
   '11564'],
  'taxi': ['11577', '11617', '9998']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'WWWWWWWWWWWWWWLWLL', 'streak': '2L'},
  'owner_id': '308032743780937728',
  'player_map': None,
  'players': ['10221',
   '10226',
   '10229',
   '11199',
   '11563',
   '11568',
   '11571',
   '11583',
   '11584',
   '11623',
   '11633',
   '2749',
   '3225',
   '3271',
   '4033',
   '4199',
   '4881',
   '4951',
   '4983',
   '5859',
   '5892',
   '7090',
   '7496',
   '7567',
   '7569',
   '7591',
   '7600',
   '8159',
   '8160',
   '8183',
   '8676',
   '9511'],
  'reserve': ['10229', '3271', '7569', '8676'],
  'roster_id': 12,
  'settings': {'fpts': 1564,
   'fpts_against': 1214,
   'fpts_against_decimal': 48,
   'fpts_decimal': 24,
   'losses': 3,
   'ppts': 1716,
   'ppts_decimal': 56,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 54,
   'waiver_position': 10,
   'wins': 15},
  'starters': ['4881',
   '4199',
   '11584',
   '5859',
   '4983',
   '7090',
   '7600',
   '7496',
   '2749',
   '5892',
   '8183'],
  'taxi': ['11568', '11571', '11633']}]

In [13]:
final_dict = {}
for item in r.json(): 
    for player in item['players']:
        final_dict[player] = item['roster_id']

In [14]:
df=pd.DataFrame(final_dict.items(), columns=['player_id', 'roster_id'])

In [15]:
TradeValueIndexDF.merge(df, left_on='index', right_on='player_id', how='left').sort_values("Value",ascending=False).to_csv("sleeper.csv", index=False)