In [47]:
import requests
import pandas as pd

r = requests.get('https://api.sleeper.app/v1/players/nfl')
r.json()
player_df=pd.read_json(r.text, orient='index')

/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_61680/1655298528.py:6: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  player_df=pd.read_json(r.text, orient='index')
/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_61680/1655298528.py:6: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  player_df=pd.read_json(r.text, orient='index')
/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_61680/1655298528.py:6: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  player_df=pd.read_json(r.text, orient='index')

In [48]:
player_df.reset_index(inplace=True)

In [49]:
player_df

,index,fantasy_positions,injury_body_part,birth_state,first_name,practice_participation,search_full_name,rotowire_id,last_name,stats_id,...,team_changed_at,player_id,depth_chart_order,position,injury_status,search_rank,practice_description,swish_id,sportradar_id,number
0,6462,[TE],None,NaN,Ellis,None,ellisrichardson,14134.0,Richardson,887183.0,...,NaT,6462,NaN,TE,None,9999999.0,None,NaN,efd6f3c3-b752-4bc2-a4f2-b776c15c3ec0,45.0
1,11255,[OL],None,NaN,Nick,None,nickamoah,NaN,Amoah,NaN,...,NaT,11255,NaN,OL,None,9999999.0,None,1052592.0,55510c00-ead2-11ed-999e-03b49558b5db,63.0
2,8842,[DB],None,NaN,Malkelm,None,malkelmmorrison,16558.0,Morrison,NaN,...,NaT,8842,NaN,CB,None,9999999.0,None,1131137.0,3c804b10-d3a8-11ec-96a0-c3471a31202c,0.0
3,7926,[TE],None,NaN,Carl,None,carltucker,15412.0,Tucker,NaN,...,NaT,7926,NaN,TE,None,426.0,None,866047.0,fde9c52b-0e2f-46e7-9b0e-9ada612ecec3,0.0
4,1875,[LB],None,NaN,C.J.,None,cjmosley,9380.0,Mosley,NaN,...,NaT,1875,1.0,LB,None,216.0,None,557173.0,bf5f7564-349a-439a-a8a9-4ddb10448a8d,57.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10581,4810,[OL],None,NaN,Kwayde,None,kwaydemiller,NaN,Miller,NaN,...,NaT,4810,NaN,OT,None,9999999.0,None,NaN,e2610400-52c1-4894-85a2-26437b5d9367,63.0
10582,918,[TE],None,NaN,Niles,None,nilespaul,7384.0,Paul,406159.0,...,NaT,918,NaN,TE,None,9999999.0,None,NaN,38f5843a-8318-4eb7-b517-c83d415e77a4,0.0
10583,1591,[OL],None,NaN,Alvin,None,alvinbailey,8704.0,Bailey,NaN,...,NaT,1591,NaN,G,None,9999999.0,None,NaN,af867ba7-f44e-4c1f-a4b3-61a9b5a7065d,78.0
10584,6744,[WR],None,NaN,Greg,None,gregward,11883.0,Ward,741292.0,...,NaT,6744,NaN,WR,None,9999999.0,None,741292.0,0832c8ad-0872-446f-ad6e-0e309e8443d1,89.0
10585,3992,None,None,NaN,Dave,None,davecaldwell,NaN,Caldwell,NaN,...,NaT,3992,NaN,None,None,9999999.0,None,NaN,,0.0

In [50]:
import pandas as pd
from roster import Roster
from tradevalue import TradeValue

In [51]:
from tradevalue import TradeValue

TradeValue_Class = TradeValue("https://www.thescore.com/news/2902917",superflex=True)
TradeValue_df = TradeValue_Class.all_dfs

INFO:root:{'base': 'https://www.thescore.com/news/2902917', 'RB': 'https://www.thescore.com/news/2817987', 'WR': 'https://www.thescore.com/news/2817988', 'TE': 'https://www.thescore.com/news/2817989', 'Draft Picks': 'https://www.thescore.com/news/2817990'}

In [52]:
TradeValue_df

                 Player  Value     Position
0        Caleb Williams   85.0         base
1   Marvin Harrison Jr.   72.0         base
2        Jayden Daniels   72.0         base
3          Malik Nabers   67.0         base
4           Rome Odunze   50.0         base
..                  ...    ...          ...
43                  NaN    8.0  Draft Picks
44                  NaN    8.0  Draft Picks
45                  NaN    7.0  Draft Picks
46                  NaN    6.0  Draft Picks
47                  NaN    5.0  Draft Picks

[508 rows x 3 columns]

In [53]:
selected_items = ["QB", "RB", "WR", "TE", "base"]
TradeValue_df=TradeValue_df[TradeValue_df["Position"].isin(selected_items)]
player_df=player_df[player_df["position"].isin(selected_items)]

In [54]:
TradeValue_df

                 Player  Value Position
0        Caleb Williams   85.0     base
1   Marvin Harrison Jr.   72.0     base
2        Jayden Daniels   72.0     base
3          Malik Nabers   67.0     base
4           Rome Odunze   50.0     base
..                  ...    ...      ...
85          Cole Turner    0.0       TE
86         Stone Smartt    0.0       TE
87        Durham Smythe    0.0       TE
88    Peyton Hendershot    0.0       TE
89           Ian Thomas    0.0       TE

[460 rows x 3 columns]

In [55]:
def col_replace(df, column_name):
    df[column_name] = df[column_name].str.replace('.', '', regex=False)
    df[column_name] = df[column_name].str.replace('Kenneth', 'Ken', regex=False)
    df[column_name] = df[column_name].str.replace(' Jr', '', regex=False)
    df[column_name] = df[column_name].str.rstrip(' III')
    df[column_name] = df[column_name].str.rstrip(' II')
    return df

In [56]:
TradeValue_df = col_replace(TradeValue_df, 'Player')
player_df = col_replace(player_df, 'full_name')

/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_61680/2038393473.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.replace('.', '', regex=False)
/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_61680/2038393473.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.replace('Kenneth', 'Ken', regex=False)
/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_61680/2038393473.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.replace(' Jr', '', regex=False)
/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_61680/2038393473.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.rstrip(' III')
/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_61680/2038393473.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.rstrip(' II')

In [57]:
TradeValueIndexDF=TradeValue_df.merge(player_df, left_on='Player', right_on='full_name', how='left')[["Player", "Value", "Position", "index"]]

In [58]:
r = requests.get('https://api.sleeper.app/v1/league/1048489707518140416/rosters')
r.json()

[{'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': None,
  'owner_id': '703398039083122688',
  'player_map': None,
  'players': ['10223',
   '10444',
   '11584',
   '11604',
   '11627',
   '1466',
   '1689',
   '19',
   '2306',
   '4018',
   '4199',
   '4866',
   '4892',
   '4943',
   '5133',
   '5870',
   '5927',
   '6111',
   '6768',
   '6783',
   '6803',
   '6819',
   '7049',
   '7527',
   '7528',
   '8143',
   '8144',
   '8188',
   '8219',
   '9500'],
  'reserve': None,
  'roster_id': 1,
  'settings': {'fpts': 0,
   'losses': 0,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 0,
   'waiver_position': 4,
   'wins': 0},
  'starters': ['6768',
   '4866',
   '4018',
   '6803',
   '5927',
   '6819',
   '1466',
   '7528',
   '4199',
   '11604',
   '4892'],
  'taxi': ['10223', '10444', '11584', '11627']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': None,
  'owner_id': '1085650223977885696',
  'player_map': None,
  'players': ['10870',
   '11557',
   '11559',
   '11567',
   '11581',
   '11588',
   '11595',
   '11610',
   '11615',
   '11625',
   '11631',
   '11635',
   '11636',
   '11637',
   '11638',
   '11640',
   '11729',
   '11821',
   '3199',
   '5248',
   '7593',
   '7670',
   '8117',
   '8121',
   '8132',
   '8408',
   '9227',
   '9494',
   '9502',
   '9753'],
  'reserve': ['11567', '11821'],
  'roster_id': 2,
  'settings': {'fpts': 0,
   'losses': 0,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 77,
   'waiver_position': 10,
   'wins': 0},
  'starters': ['11557',
   '5248',
   '11588',
   '9502',
   '8121',
   '11625',
   '11595',
   '8132',
   '11581',
   '7670',
   '0'],
  'taxi': ['11559', '11631', '11635', '11638']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': None,
  'owner_id': '474354594260971520',
  'player_map': None,
  'players': ['10213',
   '10222',
   '10235',
   '10863',
   '10871',
   '11439',
   '11560',
   '11592',
   '11624',
   '11626',
   '1339',
   '4454',
   '5857',
   '6149',
   '6770',
   '7526',
   '7610',
   '8119',
   '8138',
   '8148',
   '8159',
   '9220',
   '9224',
   '9229',
   '9479',
   '9481',
   '9487',
   '9488'],
  'reserve': None,
  'roster_id': 3,
  'settings': {'fpts': 0,
   'losses': 0,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 1,
   'waiver_position': 12,
   'wins': 0},
  'starters': ['6770',
   '8138',
   '9224',
   '7526',
   '10222',
   '9488',
   '9481',
   '11624',
   '8148',
   '8119',
   '9229'],
  'taxi': ['10213', '10871', '9479', '9487']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': None,
  'owner_id': '865796491103596544',
  'player_map': None,
  'players': ['10857',
   '10859',
   '10866',
   '11256',
   '2197',
   '2307',
   '3161',
   '4046',
   '5089',
   '5096',
   '5844',
   '5846',
   '5937',
   '6845',
   '6904',
   '6943',
   '6945',
   '7561',
   '7596',
   '7605',
   '8111',
   '8112',
   '8150',
   '8228',
   '827',
   '829',
   '9222',
   '9482',
   '9756'],
  'reserve': None,
  'roster_id': 4,
  'settings': {'fpts': 0,
   'losses': 0,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 0,
   'waiver_position': 9,
   'wins': 0},
  'starters': ['6904',
   '8150',
   '8228',
   '8112',
   '5846',
   '2197',
   '10859',
   '9756',
   '6845',
   '5844',
   '4046'],
  'taxi': ['10857', '11256', '9222', '9482']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': None,
  'owner_id': '476935207337848832',
  'player_map': None,
  'players': ['10232',
   '11562',
   '11565',
   '11573',
   '11586',
   '11596',
   '11600',
   '11605',
   '11618',
   '11620',
   '11621',
   '11630',
   '11651',
   '4144',
   '4381',
   '4464',
   '4973',
   '5012',
   '7571',
   '7594',
   '7828',
   '8131',
   '8134',
   '8135',
   '8137',
   '8230',
   '9228',
   '9486',
   '9757'],
  'reserve': ['11565'],
  'roster_id': 5,
  'settings': {'fpts': 0,
   'losses': 0,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 8,
   'waiver_position': 11,
   'wins': 0},
  'starters': ['9228',
   '11586',
   '7594',
   '8134',
   '8137',
   '11620',
   '5012',
   '10232',
   '9486',
   '11630',
   '4381'],
  'taxi': ['11596', '11600', '11618', '11651']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': None,
  'owner_id': '867881987678076928',
  'player_map': None,
  'players': ['11599',
   '11619',
   '11629',
   '11650',
   '1234',
   '1373',
   '1479',
   '2028',
   '2309',
   '3164',
   '3257',
   '4034',
   '4035',
   '4039',
   '4137',
   '4950',
   '5001',
   '5045',
   '5906',
   '5947',
   '6151',
   '6813',
   '6828',
   '6886',
   '7601',
   '8126',
   '8130',
   '8225',
   '9999'],
  'reserve': None,
  'roster_id': 6,
  'settings': {'fpts': 0,
   'losses': 0,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 1,
   'waiver_position': 3,
   'wins': 0},
  'starters': ['1373',
   '4034',
   '6813',
   '4039',
   '2309',
   '4950',
   '8130',
   '1479',
   '4035',
   '4137',
   '9999'],
  'taxi': ['11599', '11619', '11629', '11650']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': None,
  'owner_id': '713130454613573632',
  'player_map': None,
  'players': ['10219',
   '11570',
   '11574',
   '11589',
   '11603',
   '11647',
   '11748',
   '11783',
   '11815',
   '2133',
   '3286',
   '3976',
   '4017',
   '4066',
   '4972',
   '5848',
   '5850',
   '5970',
   '5995',
   '6806',
   '7021',
   '7523',
   '7538',
   '7564',
   '7585',
   '7588',
   '8110',
   '8154',
   '9221'],
  'reserve': None,
  'roster_id': 7,
  'settings': {'fpts': 0,
   'losses': 0,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 100,
   'waiver_position': 7,
   'wins': 0},
  'starters': ['7523',
   '8154',
   '9221',
   '7564',
   '5848',
   '2133',
   '4066',
   '8110',
   '7588',
   '5850',
   '4017'],
  'taxi': ['11570', '11574', '11783', '11815']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': None,
  'owner_id': '516828521139388416',
  'player_map': None,
  'players': ['10212',
   '10225',
   '11566',
   '11575',
   '11597',
   '11632',
   '11643',
   '11645',
   '11655',
   '2216',
   '2449',
   '3214',
   '6797',
   '6801',
   '6826',
   '7002',
   '7525',
   '7611',
   '8136',
   '8142',
   '8162',
   '9225',
   '9226',
   '9484',
   '9492',
   '9497',
   '9501',
   '9505',
   '9758',
   '9997'],
  'reserve': ['7002'],
  'roster_id': 8,
  'settings': {'fpts': 0,
   'losses': 0,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 0,
   'waiver_position': 2,
   'wins': 0},
  'starters': ['9758',
   '8136',
   '9226',
   '2449',
   '2216',
   '7525',
   '6826',
   '9997',
   '11632',
   '6801',
   '6797'],
  'taxi': ['11575', '11597', '11645', '11655']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': None,
  'owner_id': '411785392388325376',
  'player_map': None,
  'players': ['11377',
   '11576',
   '11616',
   '11895',
   '2078',
   '2711',
   '3294',
   '3321',
   '4082',
   '4179',
   '421',
   '4663',
   '5022',
   '5409',
   '5854',
   '5967',
   '6694',
   '6786',
   '6804',
   '7608',
   '8129',
   '8151',
   '8153',
   '8161',
   '8205',
   '8221',
   '8800',
   '9230',
   '9511'],
  'reserve': ['2078', '9511'],
  'roster_id': 9,
  'settings': {'fpts': 0,
   'losses': 0,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 0,
   'waiver_position': 8,
   'wins': 0},
  'starters': ['3294',
   '8205',
   '8151',
   '6786',
   '3321',
   '4082',
   '5022',
   '5967',
   '4663',
   '8129',
   '6804'],
  'taxi': ['11576', '11616', '9230']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'allow_pn_inactive_starters': 'on',
   'allow_pn_player_injury_status': 'off',
   'allow_pn_scoring': 'off',
   'p_nick_4381': '24 3rd',
   'p_nick_5955': '',
   'p_nick_6853': '',
   'p_nick_7670': '',
   'p_nick_8118': '',
   'p_nick_8134': '',
   'restrict_pn_scoring_starters_only': 'on'},
  'owner_id': '462028117192470528',
  'player_map': None,
  'players': ['10234',
   '10862',
   '11306',
   '11579',
   '11590',
   '11628',
   '11644',
   '1426',
   '3198',
   '4217',
   '4981',
   '4984',
   '5849',
   '6136',
   '6794',
   '6820',
   '6853',
   '6865',
   '6938',
   '7553',
   '8145',
   '8146',
   '8155',
   '8168',
   '9480',
   '9493',
   '9509',
   '96',
   '9754'],
  'reserve': None,
  'roster_id': 10,
  'settings': {'fpts': 0,
   'losses': 0,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 14,
   'waiver_position': 5,
   'wins': 0},
  'starters': ['4984',
   '9509',
   '8155',
   '6794',
   '8146',
   '11628',
   '7553',
   '9493',
   '3198',
   '1426',
   '5849'],
  'taxi': ['10234', '10862', '11644', '9480']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': None,
  'owner_id': '473952170073387008',
  'player_map': None,
  'players': ['10236',
   '11564',
   '11577',
   '11617',
   '1166',
   '1837',
   '2374',
   '3163',
   '4037',
   '4068',
   '4080',
   '4089',
   '4111',
   '4149',
   '4171',
   '4988',
   '4993',
   '5872',
   '5987',
   '6011',
   '6130',
   '6790',
   '7066',
   '7547',
   '8139',
   '8147',
   '8167',
   '8210',
   '9508',
   '9998'],
  'reserve': ['1166', '4068', '4988', '9998'],
  'roster_id': 11,
  'settings': {'fpts': 0,
   'losses': 0,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 0,
   'waiver_position': 1,
   'wins': 0},
  'starters': ['3163',
   '6790',
   '8139',
   '7547',
   '5872',
   '4037',
   '10236',
   '8167',
   '0',
   '0',
   '0'],
  'taxi': ['8147']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': None,
  'owner_id': '308032743780937728',
  'player_map': None,
  'players': ['10214',
   '10226',
   '10229',
   '11561',
   '11563',
   '11568',
   '11571',
   '11583',
   '11623',
   '11646',
   '1535',
   '2749',
   '3225',
   '3271',
   '4033',
   '4602',
   '4881',
   '4951',
   '4983',
   '5859',
   '5892',
   '7090',
   '7543',
   '7567',
   '7569',
   '7591',
   '7600',
   '8160',
   '8172',
   '8183',
   '8676'],
  'reserve': ['11583', '3271'],
  'roster_id': 12,
  'settings': {'fpts': 0,
   'losses': 0,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 5,
   'waiver_position': 6,
   'wins': 0},
  'starters': ['4881',
   '7543',
   '5892',
   '5859',
   '7569',
   '4983',
   '4033',
   '7600',
   '2749',
   '10229',
   '8183'],
  'taxi': ['11561', '11571', '11623', '11646']}]

In [59]:
final_dict = {}
for item in r.json(): 
    for player in item['players']:
        final_dict[player] = item['roster_id']

In [60]:
df=pd.DataFrame(final_dict.items(), columns=['player_id', 'roster_id'])

In [61]:
TradeValueIndexDF.merge(df, left_on='index', right_on='player_id', how='left').sort_values("Value",ascending=False).to_csv("sleeper.csv", index=False)