In [16]:
import requests
import pandas as pd

r = requests.get('https://api.sleeper.app/v1/players/nfl')
r.json()
player_df=pd.read_json(r.text, orient='index')

/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_35590/1655298528.py:6: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  player_df=pd.read_json(r.text, orient='index')
/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_35590/1655298528.py:6: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  player_df=pd.read_json(r.text, orient='index')
/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_35590/1655298528.py:6: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  player_df=pd.read_json(r.text, orient='index')

In [17]:
player_df.reset_index(inplace=True)

In [18]:
player_df

,index,last_name,swish_id,rotowire_id,search_last_name,hashtag,depth_chart_position,number,search_first_name,sport,...,gsis_id,team,birth_city,oddsjam_id,rotoworld_id,sportradar_id,yahoo_id,search_full_name,height,first_name
0,6462,Richardson,NaN,14134.0,richardson,#ellisrichardson-NFL-FA-45,None,45.0,ellis,nfl,...,00-0035057,None,NaN,None,NaN,efd6f3c3-b752-4bc2-a4f2-b776c15c3ec0,32262.0,ellisrichardson,75,Ellis
1,11255,Amoah,1052592.0,NaN,amoah,#nickamoah-NFL-FA-63,None,63.0,nick,nfl,...,None,None,NaN,None,NaN,55510c00-ead2-11ed-999e-03b49558b5db,NaN,nickamoah,74,Nick
2,8842,Morrison,1131137.0,16558.0,morrison,#malkelmmorrison-NFL-FA-0,None,0.0,malkelm,nfl,...,None,None,NaN,None,NaN,3c804b10-d3a8-11ec-96a0-c3471a31202c,NaN,malkelmmorrison,70,Malkelm
3,7926,Tucker,866047.0,15412.0,tucker,#carltucker-NFL-FA-0,None,0.0,carl,nfl,...,None,None,NaN,None,NaN,fde9c52b-0e2f-46e7-9b0e-9ada612ecec3,NaN,carltucker,74,Carl
4,1875,Mosley,557173.0,9380.0,mosley,#cjmosley-NFL-NYJ-57,MLB,57.0,cj,nfl,...,00-0031296,NYJ,NaN,97CDFFA7FA4D,9631.0,bf5f7564-349a-439a-a8a9-4ddb10448a8d,27545.0,cjmosley,74,C.J.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10583,4810,Miller,NaN,NaN,miller,#kwaydemiller-NFL-FA-63,None,63.0,kwayde,nfl,...,None,None,NaN,None,NaN,e2610400-52c1-4894-85a2-26437b5d9367,30668.0,kwaydemiller,79,Kwayde
10584,918,Paul,NaN,7384.0,paul,#nilespaul-NFL-FA-0,None,0.0,niles,nfl,...,00-0028093,None,NaN,None,6661.0,38f5843a-8318-4eb7-b517-c83d415e77a4,24942.0,nilespaul,73,Niles
10585,1591,Bailey,NaN,8704.0,bailey,#alvinbailey-NFL-FA-78,None,78.0,alvin,nfl,...,None,None,NaN,None,8690.0,af867ba7-f44e-4c1f-a4b3-61a9b5a7065d,26894.0,alvinbailey,"6'3""",Alvin
10586,6744,Ward,741292.0,11883.0,ward,#gregward-NFL-FA-89,None,89.0,greg,nfl,...,00-0033733,None,NaN,3349E777E3F6,12815.0,0832c8ad-0872-446f-ad6e-0e309e8443d1,30715.0,gregward,71,Greg
10587,3992,Caldwell,NaN,NaN,caldwell,#davecaldwell-NFL-FA-0,None,0.0,dave,nfl,...,None,None,NaN,None,9502.0,,NaN,davecaldwell,,Dave

In [19]:
import pandas as pd
from roster import Roster
from tradevalue import TradeValue

In [20]:
from tradevalue import TradeValue

TradeValue_Class = TradeValue("https://www.thescore.com/nfl/news/3077352/fantasy-trade-value-chart-week-3")
TradeValue_df = TradeValue_Class.all_dfs

INFO:root:{'base': 'https://www.thescore.com/nfl/news/3077352/fantasy-trade-value-chart-week-3', 'RB': 'https://thescore.com/news/3066601', 'WR': 'https://thescore.com/news/3066602', 'TE': 'https://thescore.com/news/3066603'}

In [21]:
TradeValue_df

                Player  Value Position
0           Josh Allen   41.0     base
1          Jalen Hurts   40.0     base
2        Lamar Jackson   39.0     base
3   Patrick Mahomes II   35.0     base
4          C.J. Stroud   30.0     base
..                 ...    ...      ...
65         Jared Wiley    0.0       TE
66         Lucas Krull    0.0       TE
67        Luke Farrell    0.0       TE
68       Adam Trautman    0.0       TE
69       Drew Ogletree    0.0       TE

[315 rows x 3 columns]

In [22]:
selected_items = ["QB", "RB", "WR", "TE", "base"]
TradeValue_df=TradeValue_df[TradeValue_df["Position"].isin(selected_items)]
player_df=player_df[player_df["position"].isin(selected_items)]

In [23]:
TradeValue_df

                Player  Value Position
0           Josh Allen   41.0     base
1          Jalen Hurts   40.0     base
2        Lamar Jackson   39.0     base
3   Patrick Mahomes II   35.0     base
4          C.J. Stroud   30.0     base
..                 ...    ...      ...
65         Jared Wiley    0.0       TE
66         Lucas Krull    0.0       TE
67        Luke Farrell    0.0       TE
68       Adam Trautman    0.0       TE
69       Drew Ogletree    0.0       TE

[315 rows x 3 columns]

In [24]:
def col_replace(df, column_name):
    df[column_name] = df[column_name].str.replace('.', '', regex=False)
    df[column_name] = df[column_name].str.replace('Kenneth', 'Ken', regex=False)
    df[column_name] = df[column_name].str.replace(' Jr', '', regex=False)
    df[column_name] = df[column_name].str.rstrip(' III')
    df[column_name] = df[column_name].str.rstrip(' II')
    return df

In [25]:
TradeValue_df = col_replace(TradeValue_df, 'Player')
player_df = col_replace(player_df, 'full_name')

/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_35590/2038393473.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.replace('.', '', regex=False)
/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_35590/2038393473.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.replace('Kenneth', 'Ken', regex=False)
/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_35590/2038393473.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.replace(' Jr', '', regex=False)
/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_35590/2038393473.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.rstrip(' III')
/var/folders/k3/m2tddk1x3fvd5dtgwd9h1jcr0000gp/T/ipykernel_35590/2038393473.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.rstrip(' II')

In [26]:
TradeValueIndexDF=TradeValue_df.merge(player_df, left_on='Player', right_on='full_name', how='left')[["Player", "Value", "Position", "index"]]

In [27]:
r = requests.get('https://api.sleeper.app/v1/league/1048489707518140416/rosters')
r.json()

[{'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'WWWL', 'streak': '1L'},
  'owner_id': '703398039083122688',
  'player_map': None,
  'players': ['10223',
   '10444',
   '11604',
   '11627',
   '1466',
   '1689',
   '19',
   '2306',
   '4018',
   '4029',
   '4866',
   '4892',
   '4943',
   '5133',
   '5870',
   '5927',
   '5985',
   '6111',
   '6768',
   '6783',
   '6803',
   '6819',
   '7527',
   '7528',
   '7543',
   '8143',
   '8144',
   '8219',
   '9500'],
  'reserve': ['8219', '9500'],
  'roster_id': 1,
  'settings': {'fpts': 295,
   'fpts_against': 188,
   'fpts_against_decimal': 64,
   'fpts_decimal': 28,
   'losses': 1,
   'ppts': 373,
   'ppts_decimal': 62,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 0,
   'waiver_position': 5,
   'wins': 3},
  'starters': ['6768',
   '7543',
   '8143',
   '8144',
   '5927',
   '6819',
   '1466',
   '6803',
   '4866',
   '4018',
   '4892'],
  'taxi': ['10223', '10444', '11627']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'LLLL', 'streak': '4L'},
  'owner_id': '1085650223977885696',
  'player_map': None,
  'players': ['10216',
   '10867',
   '11199',
   '11557',
   '11559',
   '11567',
   '11581',
   '11610',
   '11625',
   '11631',
   '11635',
   '11636',
   '11637',
   '11638',
   '11640',
   '11729',
   '5248',
   '5284',
   '6039',
   '6427',
   '7568',
   '7593',
   '7670',
   '8117',
   '8121',
   '8132',
   '8142',
   '8195',
   '9227',
   '9494',
   '9502',
   '9753'],
  'reserve': ['11557', '11567', '11610', '11638'],
  'roster_id': 2,
  'settings': {'fpts': 148,
   'fpts_against': 257,
   'fpts_against_decimal': 50,
   'fpts_decimal': 40,
   'losses': 4,
   'ppts': 211,
   'ppts_decimal': 90,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 78,
   'waiver_position': 12,
   'wins': 0},
  'starters': ['0',
   '5248',
   '9753',
   '9502',
   '8121',
   '11625',
   '7568',
   '8132',
   '8117',
   '7670',
   '8142'],
  'taxi': ['11559', '11631', '11635', '11637']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'LWLL', 'streak': '2L'},
  'owner_id': '474354594260971520',
  'player_map': None,
  'players': ['10213',
   '10222',
   '10235',
   '10863',
   '10871',
   '11439',
   '11560',
   '11592',
   '11624',
   '11626',
   '1339',
   '4454',
   '5857',
   '6149',
   '6770',
   '7526',
   '7610',
   '8119',
   '8138',
   '8148',
   '8159',
   '9220',
   '9224',
   '9229',
   '9479',
   '9481',
   '9487',
   '9488'],
  'reserve': None,
  'roster_id': 3,
  'settings': {'fpts': 292,
   'fpts_against': 340,
   'fpts_against_decimal': 70,
   'fpts_decimal': 2,
   'losses': 3,
   'ppts': 328,
   'ppts_decimal': 12,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 1,
   'waiver_position': 2,
   'wins': 1},
  'starters': ['6770',
   '8138',
   '11439',
   '7526',
   '10222',
   '9488',
   '1339',
   '11624',
   '8148',
   '5857',
   '9229'],
  'taxi': ['10213', '10871', '9479', '9487']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'WLLW', 'streak': '1W'},
  'owner_id': '865796491103596544',
  'player_map': None,
  'players': ['10217',
   '10857',
   '10859',
   '10866',
   '11256',
   '11582',
   '2197',
   '2307',
   '3161',
   '4046',
   '4082',
   '5022',
   '5846',
   '5937',
   '5967',
   '6845',
   '6904',
   '6943',
   '6945',
   '7561',
   '7596',
   '8111',
   '8112',
   '8116',
   '8150',
   '8206',
   '8228',
   '827',
   '829',
   '9482',
   '9756'],
  'reserve': ['2307', '7561'],
  'roster_id': 4,
  'settings': {'fpts': 261,
   'fpts_against': 264,
   'fpts_against_decimal': 10,
   'fpts_decimal': 72,
   'losses': 2,
   'ppts': 306,
   'ppts_decimal': 2,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 6,
   'waiver_position': 11,
   'wins': 2},
  'starters': ['6904',
   '8150',
   '5967',
   '8112',
   '5846',
   '2197',
   '10859',
   '6943',
   '5022',
   '5937',
   '4046'],
  'taxi': ['10857', '10866', '11256', '9482']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'LLLL', 'streak': '4L'},
  'owner_id': '476935207337848832',
  'player_map': None,
  'players': ['10212',
   '10232',
   '11562',
   '11565',
   '11586',
   '11596',
   '11600',
   '11605',
   '11618',
   '11620',
   '11621',
   '11630',
   '11651',
   '4144',
   '4314',
   '4381',
   '4464',
   '4973',
   '5008',
   '5012',
   '7571',
   '7594',
   '7828',
   '8131',
   '8134',
   '8135',
   '8137',
   '8230',
   '9228',
   '9486',
   '9757'],
  'reserve': ['11565', '9757'],
  'roster_id': 5,
  'settings': {'fpts': 130,
   'fpts_against': 251,
   'fpts_against_decimal': 22,
   'fpts_decimal': 60,
   'losses': 4,
   'ppts': 208,
   'ppts_decimal': 84,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 11,
   'waiver_position': 8,
   'wins': 0},
  'starters': ['9228',
   '8230',
   '7594',
   '8134',
   '8137',
   '11620',
   '5012',
   '10232',
   '9486',
   '11630',
   '4381'],
  'taxi': ['11596', '11600', '11618', '11651']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'WWWW', 'streak': '4W'},
  'owner_id': '867881987678076928',
  'player_map': None,
  'players': ['11599',
   '11619',
   '11629',
   '11650',
   '1234',
   '1373',
   '1479',
   '2028',
   '2309',
   '3164',
   '3257',
   '4034',
   '4035',
   '4039',
   '4137',
   '4147',
   '4950',
   '5001',
   '5045',
   '5096',
   '5906',
   '5947',
   '6151',
   '6813',
   '6828',
   '7601',
   '8126',
   '8130',
   '8225',
   '8408',
   '9999'],
  'reserve': ['4034', '6828', '7601'],
  'roster_id': 6,
  'settings': {'fpts': 318,
   'fpts_against': 195,
   'fpts_against_decimal': 36,
   'fpts_decimal': 62,
   'losses': 0,
   'ppts': 382,
   'ppts_decimal': 94,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 22,
   'waiver_position': 4,
   'wins': 4},
  'starters': ['1373',
   '4035',
   '6813',
   '4039',
   '2309',
   '4950',
   '8130',
   '8408',
   '5045',
   '4137',
   '2028'],
  'taxi': ['11599', '11619', '11629', '11650']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'LLWW', 'streak': '2W'},
  'owner_id': '713130454613573632',
  'player_map': None,
  'players': ['10219',
   '11570',
   '11574',
   '11589',
   '11647',
   '11748',
   '11783',
   '2133',
   '3286',
   '4017',
   '4040',
   '4066',
   '4972',
   '5848',
   '5850',
   '5970',
   '5995',
   '6271',
   '6806',
   '7021',
   '7523',
   '7538',
   '7564',
   '7585',
   '7587',
   '7588',
   '8110',
   '8154',
   '9221'],
  'reserve': None,
  'roster_id': 7,
  'settings': {'fpts': 262,
   'fpts_against': 235,
   'fpts_against_decimal': 16,
   'fpts_decimal': 38,
   'losses': 2,
   'ppts': 295,
   'ppts_decimal': 38,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 100,
   'waiver_position': 6,
   'wins': 2},
  'starters': ['7523',
   '5850',
   '9221',
   '7564',
   '5970',
   '2133',
   '4066',
   '6806',
   '7588',
   '8154',
   '4017'],
  'taxi': ['11570', '11574', '11748', '11783']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'WWWW', 'streak': '4W'},
  'owner_id': '516828521139388416',
  'player_map': None,
  'players': ['10225',
   '11566',
   '11575',
   '11597',
   '11632',
   '11643',
   '11645',
   '11655',
   '2216',
   '2449',
   '3214',
   '6797',
   '6801',
   '6826',
   '7002',
   '7525',
   '7602',
   '7611',
   '8136',
   '8162',
   '9225',
   '9226',
   '9484',
   '9492',
   '9497',
   '9501',
   '9505',
   '9758',
   '9997'],
  'reserve': None,
  'roster_id': 8,
  'settings': {'fpts': 355,
   'fpts_against': 266,
   'fpts_against_decimal': 84,
   'fpts_decimal': 76,
   'losses': 0,
   'ppts': 403,
   'ppts_decimal': 42,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 2,
   'waiver_position': 3,
   'wins': 4},
  'starters': ['9758',
   '8136',
   '7611',
   '2449',
   '9997',
   '7525',
   '6826',
   '2216',
   '11632',
   '9226',
   '11566'],
  'taxi': ['11575', '11597', '11645', '11655']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'LLLL', 'streak': '4L'},
  'owner_id': '411785392388325376',
  'player_map': None,
  'players': ['1049',
   '11435',
   '11576',
   '11616',
   '2078',
   '2711',
   '3294',
   '3321',
   '3634',
   '4179',
   '421',
   '4234',
   '4663',
   '5032',
   '5121',
   '5185',
   '5844',
   '5854',
   '6598',
   '6786',
   '6804',
   '6869',
   '6960',
   '7608',
   '8129',
   '8151',
   '8161',
   '8180',
   '8205',
   '9230',
   '9511'],
  'reserve': ['2078', '5844', '9511'],
  'roster_id': 9,
  'settings': {'fpts': 220,
   'fpts_against': 364,
   'fpts_against_decimal': 96,
   'fpts_decimal': 12,
   'losses': 4,
   'ppts': 280,
   'ppts_decimal': 88,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 32,
   'waiver_position': 10,
   'wins': 0},
  'starters': ['3294',
   '8205',
   '8151',
   '6786',
   '3321',
   '5185',
   '6869',
   '3634',
   '4663',
   '6598',
   '421'],
  'taxi': ['11576', '11616', '9230']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'allow_pn_inactive_starters': 'on',
   'allow_pn_player_injury_status': 'off',
   'allow_pn_scoring': 'off',
   'p_nick_4381': '24 3rd',
   'p_nick_5955': '',
   'p_nick_6853': '',
   'p_nick_7670': '',
   'p_nick_8118': '',
   'p_nick_8134': '',
   'record': 'WWWW',
   'restrict_pn_scoring_starters_only': 'on',
   'streak': '4W'},
  'owner_id': '462028117192470528',
  'player_map': None,
  'players': ['10862',
   '11306',
   '11579',
   '11590',
   '11628',
   '11644',
   '11834',
   '1426',
   '3198',
   '4217',
   '4981',
   '4984',
   '5849',
   '6136',
   '6794',
   '6820',
   '6853',
   '6865',
   '6938',
   '7049',
   '7553',
   '8145',
   '8146',
   '8155',
   '8168',
   '9480',
   '9493',
   '9509',
   '96',
   '9754'],
  'reserve': ['11579', '6820', '9493'],
  'roster_id': 10,
  'settings': {'fpts': 350,
   'fpts_against': 266,
   'fpts_against_decimal': 60,
   'fpts_decimal': 86,
   'losses': 0,
   'ppts': 419,
   'ppts_decimal': 44,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 16,
   'waiver_position': 9,
   'wins': 4},
  'starters': ['4984',
   '9509',
   '8155',
   '6794',
   '8146',
   '11628',
   '4217',
   '4981',
   '3198',
   '7553',
   '5849'],
  'taxi': ['10862', '11590', '11644', '9480']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'LLLL', 'streak': '4L'},
  'owner_id': '473952170073387008',
  'player_map': None,
  'players': ['10236',
   '11564',
   '11577',
   '11617',
   '1166',
   '1837',
   '2374',
   '3163',
   '4037',
   '4068',
   '4080',
   '4089',
   '4111',
   '4149',
   '4171',
   '4988',
   '4993',
   '5872',
   '5987',
   '6011',
   '6130',
   '6790',
   '7066',
   '7547',
   '8139',
   '8167',
   '8210',
   '9508',
   '9998'],
  'reserve': ['4988'],
  'roster_id': 11,
  'settings': {'fpts': 253,
   'fpts_against': 362,
   'fpts_against_decimal': 68,
   'fpts_decimal': 40,
   'losses': 4,
   'ppts': 324,
   'ppts_decimal': 44,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 0,
   'waiver_position': 1,
   'wins': 0},
  'starters': ['3163',
   '6790',
   '5987',
   '7547',
   '5872',
   '4037',
   '10236',
   '8167',
   '6130',
   '2374',
   '1166'],
  'taxi': ['11577', '11617', '9998']},
 {'co_owners': None,
  'keepers': None,
  'league_id': '1048489707518140416',
  'metadata': {'record': 'WWWW', 'streak': '4W'},
  'owner_id': '308032743780937728',
  'player_map': None,
  'players': ['4033',
   '11568',
   '8172',
   '4951',
   '7600',
   '8123',
   '11623',
   '4199',
   '11615',
   '11583',
   '5892',
   '7567',
   '11563',
   '8183',
   '7090',
   '10214',
   '2749',
   '8207',
   '10229',
   '4983',
   '8676',
   '7591',
   '5859',
   '8160',
   '10226',
   '7569',
   '1535',
   '3271',
   '4881',
   '11633',
   '3225',
   '11571',
   '11584'],
  'reserve': ['11583', '11615', '3271', '4951'],
  'roster_id': 12,
  'settings': {'fpts': 349,
   'fpts_against': 245,
   'fpts_against_decimal': 30,
   'fpts_decimal': 90,
   'losses': 0,
   'ppts': 356,
   'ppts_decimal': 30,
   'ties': 0,
   'total_moves': 0,
   'waiver_budget_used': 5,
   'waiver_position': 7,
   'wins': 4},
  'starters': ['4881',
   '4199',
   '5892',
   '7569',
   '4983',
   '8676',
   '7600',
   '10226',
   '7090',
   '10229',
   '8183'],
  'taxi': ['11568', '11571', '11623', '11633']}]

In [28]:
final_dict = {}
for item in r.json(): 
    for player in item['players']:
        final_dict[player] = item['roster_id']

In [29]:
df=pd.DataFrame(final_dict.items(), columns=['player_id', 'roster_id'])

In [30]:
TradeValueIndexDF.merge(df, left_on='index', right_on='player_id', how='left').sort_values("Value",ascending=False).to_csv("sleeper.csv", index=False)